// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package o11y

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RemoteApiRequest struct {
	Id              int32              `db:"id" json:"id"`
	Url             string             `db:"url" json:"url"`
	Method          string             `db:"method" json:"method"`
	RequestHeaders  []byte             `db:"request_headers" json:"request_headers"`
	RequestBody     pgtype.Text        `db:"request_body" json:"request_body"`
	ResponseTimeMs  int64              `db:"response_time_ms" json:"response_time_ms"`
	ResponseHeaders []byte             `db:"response_headers" json:"response_headers"`
	ResponseBody    pgtype.Text        `db:"response_body" json:"response_body"`
	StatusCode      int32              `db:"status_code" json:"status_code"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
